wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=olenepal
    ports:
     - "9898:80"
    volumes:
     - ./code:/code
     - ./html:/var/www/html
mariadb:
    image: mariadb:latest
    environment:
     - MYSQL_ROOT_PASSWORD=olenepal
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
